spring:
  application:
    name: User-service
  datasource:
    url: jdbc:mysql://localhost:3306/Amazon
    username: root
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | validate | update | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
server:
  port: 9090




logging:
  level:
    org.hibernate.SQL: DEBUG
