spring:

  application:
    name: User-service

#  profiles:
#    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/Amazon
    username: root
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | validate | update | none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: false
#        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  # Fails when we pass field which is not related/compatible with our Object
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  data:
    redis:
      host: 54.210.121.79
      port: 6379
      password:
      timeout: 5000ms

server:
  port: 9090




#logging:
#  level:
#    root: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

